### ISSUE TITLE
Unable to get Candle to launch

### ISSUE THREAD

**Issue by kilt-er** [pihnat/rpi-Candle#5]
Hello!
I am unable to get Candle to launch on my Rpi4 (tried 2 different machines) -- I downloaded the executable, and when I double click on the "Candle" file, nothing happens (after selecting the "do not prompt for executables" option).  I saw that Qt5 is a build requirement which I interpreted to mean that I did not need Qt5 installed to run the Candle executable.  Is that not the case?

I also spent about 2 hours trying to follow the instructions here to get Qt5 running:  https://www.interelectronix.com/qt-on-the-raspberry-pi-4.html

Made it all the way here:
rsync -avz root@:/lib sysroot
rsync -avz root@:/usr/include sysroot/usr
rsync -avz root@:/usr/lib sysroot/usr
rsync -avz root@:/opt/vc sysroot/opt

but wasn't able to get ssh working.

Then, I tried the instructions here:  https://raspberrypi.stackexchange.com/questions/110955/installing-qt-on-raspberry-pi-4
and got Qt installed -- but still, no dice when I click the exe.  

Sorry for the basic question here -- love Candle and would really like to simplify my CNC setup by just having an RPi with a touch screen launch my CNC machine.

Any help appreciated!

**Comment by kilt-er** [comment]
I just followed the wiki instructions for installing Qt5 and building Candle (great instructions, btw!).... and it worked!  I then went back and tried the executable from github -- and that worked too!  So I guess I answered my own questions above (you need to have Qt5 installed) and I must have fixed whatever was wrong with my Qt5 installation by following the instructions here.

Thank you for the outstanding work here -- so excited to run my CNC from my RPi4!!!

**Comment by pihnat** [comment]
Qt5 is required to build Candle but if you download the executable from
https://github.com/pihnat/rpi-Candle/releases/download/v1.1/Candle_1.1.8_for_raspi4.zip
you shouldn't need to install Qt5 at all. It should run stand-alone just like the Windows version.
This is described in the first part of the wiki
https://github.com/pihnat/rpi-Candle/wiki

**Comment by kilt-er** [comment]
> Qt5 is required to build Candle but if you download the executable from
> https://github.com/pihnat/rpi-Candle/releases/download/v1.1/Candle_1.1.8_for_raspi4.zip
> you shouldn't need to install Qt5 at all. It should run stand-alone just like the Windows version.
> This is described in the first part of the wiki
> https://github.com/pihnat/rpi-Candle/wiki

Thanks for confirming.  This makes sense, but it somehow didn't work until I followed the wiki steps and installed Qt5.  I can't point to why, but that was what happened.

**Comment by garubi** [comment]
On raspberry PI 3 running raspian.
I confirm that I had to install libqt5serialport5-dev 
with sudo apt-get install libqt5serialport5-dev
in order to be able to launch Cande

**Comment by pihnat** [comment]
Thanks for the update. When I get a chance I'll check why libqt5serialport5-dev needs to be installed. From memory I didn't have to on my raspi4 setup.
BTW Candle runs very slowly on a raspi3 so if you can, install it on a raspi4. It's much more responsive, just like running on a PC.

**Comment by rdhunkins** [comment]
I'm hoping to run Candle on a RPi400.
I've tried everything here an in the other relevant issues, but no response from clicking the Candle icon.
I tried to run the executable in the terminal as well and get "Command not found" This was done n the Candle directory where the executable is.
I'm not sure what else to try, I'd prefer not to build it.

**Comment by pihnat** [comment]
Check 'closed issue' #7, "Executable won't start". Might just need the permissions to be changed to execute. Either right click the executable & change it there or in Terminal type
sudo chmod +x Candle
