### ISSUE TITLE
Octoprint Install - Application to run Executable?

### ISSUE THREAD

**Issue by eightheads** [pihnat/rpi-Candle#6]
Hi, I'm trying to run this on top of an Octoprint install on my Pi4. I have to install the desktop environment as by default the Octoprint install is headless. The desktop environment is very basic on what comes installed and does not seem to have an application to open the Candle executable by default. It's very rare that I run Pis in a desktop environment so I'm a little lost on this side of things. Is there an application you can recommend that will open the Candle executable? Thanks!

**Comment by pihnat** [comment]
Hi, I don't have any experience with Octoprint but all I vaguely remember about it is that it allows you to talk to a 3D printer over wifi.
This is different to how Candle works. Candle communicates with an Arduino Uno and it's the Arduino which is connected to the actual CNC motor controllers. So I think that Candle and Octoprint are very different in their operation.
Maybe someone reading this might have more info to share about this.

**Comment by eightheads** [comment]
Octoprint is running a Debian installation on my Raspberry Pi. I'm trying
to run rpi-Candle in the desktop environment of the Pi.

**Comment by pihnat** [comment]
After you copy the 'Candle' folder into \home\pi and double click the executable in that folder, what happens?

**Comment by eightheads** [comment]
<img width="1192" alt="Screen Shot 2021-03-25 at 7 37 00 PM" src="https://user-images.githubusercontent.com/13207144/112560701-bde3b500-8da1-11eb-941b-fa991f7b9b6e.png">
<img width="1132" alt="Screen Shot 2021-03-25 at 7 37 38 PM" src="https://user-images.githubusercontent.com/13207144/112560706-c0460f00-8da1-11eb-80e6-4baf0e1e32d0.png">

**Comment by pihnat** [comment]
I don't have a raspi with me right now but from memory you need to right click the executable file's icon and select 'properties'. There you can set it to be executable. I don't remember the exact wording of the setting but if it's not obvious I'll reply later once I check on my raspi.

**Comment by eightheads** [comment]
If you get a chance, can you take a look and let me know what the Open With: section looks like on your Pi install? Thanks!
<img width="443" alt="Screen Shot 2021-03-25 at 9 22 02 PM" src="https://user-images.githubusercontent.com/13207144/112568307-3ea9ad80-8db0-11eb-99a3-1a9d6edd97aa.png">

**Comment by eightheads** [comment]
And yes, I know XTerm is not the proper application to open with, but was trying the few options available.

**Comment by eightheads** [comment]
@pihnat I've made some headway. I had to install Qt5 and libqt5serialport5-dev to get it to open. However, I am now running into the Open File Dialog issue as seen here: https://github.com/pihnat/rpi-Candle/issues/2. I am able to open NC files directly using the Candle executable using open with custom command line option. So at least I have it opening now and seems to be working. I will test more over the weekend.

**Comment by pihnat** [comment]
You shouldn't need to install qt at all unless you're editing the source code. I have it running on my raspi4 without it.
On my setup under the executable file's "Properties" the "Open with:" box has nothing in it. Under the "Permissions" tab I had set the "Execute:" dropdown menu to "Anyone".
And of course in File Manager under 'Edit", "Preferences" I ticked the box "Don't ask options on launch executable file" as described in the wiki. All this stops is having a popup box open each time to ask if you want to run the program.

**Comment by eightheads** [comment]
libqt5serialport5-dev seems to have been the main thing preventing it from opening in my case. But it is running now, thanks!

**Comment by jcampbel2** [comment]
Wouldnt run after extract so installed  libqt5serialport5-dev as suggested using 

sudo apt-get install libqt5serialport5-dev

this resolved issued

**Comment by pihnat** [comment]
Thanks for confirming that the installation of libqt5serialport5-dev solves the problem.
