### ISSUE TITLE
Executable won't start.

### ISSUE THREAD

**Issue by RonaldDegenkamp** [pihnat/rpi-Candle#7]
pihnat,

Nice work. Found I had to:
 sudo chmod +x Candle

To get candle to run.
Somehow the execute flag got wiped in your ZIP file.
Could you add it in the WIKI.
Have it running now on a rpi 4B with joy-it 7" 1024x600 touch screen.
It even jogs from the touch screen!
Hope  the 1.2 version gets released soon would be nice to be able to shift the panels.

Greetings
Ronald

**Comment by pihnat** [comment]
I changed the executable's permission to 'Anyone' in the zip file so 'chmod +x' shouldn't be necessary now. Let me know if there's any problems.

**Comment by RonaldDegenkamp** [comment]
Works for me.
Thanks
