### ISSUE TITLE
Console does not accept input

### ISSUE THREAD

**Issue by mcinquino** [pihnat/rpi-Candle#8]
Hello,

I searched for a solution to the problem I am having of not being able to type any commands in the console window. I did not find that anyone else was having this problem. This leads me to believe it is something I am doing? Does anyone have the same problem or is there something I am missing? I am using candle version 1.1.8 on a Rasp Pi 4. I installed using the instruction from this site. Other than this issue it works great. Very responsive. Any help would be appreciated.

Thanks You.

**Comment by pihnat** [comment]
Hi mcinquino,
Firstly I assume you have an Arduino Uno running grbl plugged into the raspi4's USB port? You won't be able to type anything in the console if there's no Arduino attached, it'll just produce an error message.
Secondly, you can't type directly into the console window. Commands are entered in the smaller box directly below the console window. When you press 'enter' the command you typed will 'move' up to the console window and execute.

![Console](https://user-images.githubusercontent.com/15223225/117589815-532ee300-b16f-11eb-862e-8d417d42d1af.jpg)

**Comment by mcinquino** [comment]
Hello pihnat,

Thank you for the response. I do have an arduino connected and communicating. When I attempt to enter text in the smaller box it is like it is not accepting focus. No cursor shows and I am not able to enter text. I almost wonder if the text is set to white with a white background and I just can't see it. To test this I used the clear button then entered a G0 x0.0 to see if I could send it but I got no reaction from the software. I had jogged the x away from 0 prior to attempting this. I changed the text color in the setting to red just to see and that just changed it on the overlay of the backplot area. What makes me think it might be a text color issue is that when I right mouse click on the console window I do get a menu that pops up and I can just make out that it says copy and select all but it is white text. There is nothing in the context window and it might know that and that is why it is "grayed out"?

**Comment by mcinquino** [comment]
Hello again,

I found that it was because I had keyboard control selected in the jog function. With that not selected it works as expected. Sorry for not noticing this earlier. It was probably outlined somewhere and I missed it. I love the software looking forward to getting my machine up and running with it.

**Comment by pihnat** [comment]
Yes you are right. I forgot about this since I only use the jog buttons with the mouse not the keyboard.
Thanks for posting the solution in case it comes up again.

**Comment by pihnat** [comment]
The version I compiled was for 32-bit OS but I can't remember if it was Buster or Bullseye. I don't know if anyone has tested it for Bookworm but a start would be to try the 32-bit version of Bookworm instead to see if it runs under that.
